--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nhanaz-pm-pl/CommandBlocker
build-by-default: true
branches:
- master
projects:
  CommandBlocker:
    path: ""
    libs:
      - src: JinodkDevTeam/Commando/Commando
        version: ^3.2.0
...
