---
name: CommandBlocker
version: 1.0.0
main: NhanAZ\CommandBlocker\Main
api: 5.0.0
website: https://github.com/NhanAZ
description: Block players using specified commands
authors:
  - NhanAZ
  - phuongaz
...
